"""initial schema

Revision ID: cc95e56d8f01
Revises: 
Create Date: 2026-09-04 16:29:55.304658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = 'cc95e56d8f01'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Manufacturer',
    sa.Column('ManufacturerId', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('Name', sa.NVARCHAR(length=200), nullable=False),
    sa.Column('NormalizedName', sa.NVARCHAR(length=200), nullable=False),
    sa.Column('Country', sa.NVARCHAR(length=100), nullable=True),
    sa.Column('Status', sa.NVARCHAR(length=20), nullable=False),
    sa.Column('Metadata', sa.NVARCHAR(), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.Column('UpdatedAt', sa.DateTime(), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.PrimaryKeyConstraint('ManufacturerId', name=op.f('pk_Manufacturer')),
    sa.UniqueConstraint('NormalizedName', name=op.f('uq_Manufacturer_NormalizedName'))
    )
    op.create_table('Source',
    sa.Column('SourceId', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('SourceCode', sa.NVARCHAR(length=50), nullable=False),
    sa.Column('Name', sa.NVARCHAR(length=200), nullable=False),
    sa.Column('NormalizedName', sa.NVARCHAR(length=200), nullable=False),
    sa.Column('SourceType', sa.NVARCHAR(length=50), nullable=True),
    sa.Column('Status', sa.NVARCHAR(length=20), nullable=False),
    sa.Column('Description', sa.NVARCHAR(), nullable=True),
    sa.Column('Metadata', sa.NVARCHAR(), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.Column('UpdatedAt', sa.DateTime(), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.CheckConstraint("Status IN ('ACTIVE','INACTIVE','MERGED')", name=op.f('ck_Source_status_valid')),
    sa.PrimaryKeyConstraint('SourceId', name=op.f('pk_Source')),
    sa.UniqueConstraint('NormalizedName', name=op.f('uq_Source_NormalizedName')),
    sa.UniqueConstraint('SourceCode', name=op.f('uq_Source_SourceCode'))
    )
    op.create_table('Brand',
    sa.Column('BrandId', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ManufacturerId', sa.BigInteger(), nullable=False),
    sa.Column('Name', sa.NVARCHAR(length=200), nullable=False),
    sa.Column('NormalizedName', sa.NVARCHAR(length=200), nullable=False),
    sa.Column('Status', sa.NVARCHAR(length=20), nullable=False),
    sa.Column('Metadata', sa.NVARCHAR(), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.Column('UpdatedAt', sa.DateTime(), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.ForeignKeyConstraint(['ManufacturerId'], ['Manufacturer.ManufacturerId'], name=op.f('fk_Brand_ManufacturerId_Manufacturer')),
    sa.PrimaryKeyConstraint('BrandId', name=op.f('pk_Brand')),
    sa.UniqueConstraint('ManufacturerId', 'NormalizedName', name='uq_manufacturer_name')
    )
    op.create_table('ImportBatch',
    sa.Column('ImportBatchId', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('SourceId', sa.BigInteger(), nullable=True),
    sa.Column('Status', sa.NVARCHAR(length=20), nullable=False),
    sa.Column('ParserVersion', sa.NVARCHAR(length=50), nullable=True),
    sa.Column('NormalizerVersion', sa.NVARCHAR(length=50), nullable=True),
    sa.Column('FileCount', sa.Integer(), nullable=False),
    sa.Column('RowCount', sa.Integer(), nullable=False),
    sa.Column('AcceptedCount', sa.Integer(), nullable=False),
    sa.Column('RejectedCount', sa.Integer(), nullable=False),
    sa.Column('WarningCount', sa.Integer(), nullable=False),
    sa.Column('ErrorCount', sa.Integer(), nullable=False),
    sa.Column('CreatedBy', sa.NVARCHAR(length=200), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.Column('UpdatedAt', sa.DateTime(), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.CheckConstraint("Status IN ('UPLOADED','ANALYZING','ANALYZED','VALIDATING','NEEDS_REVIEW','APPROVED','IMPORTING','COMPLETED','FAILED','CANCELLED')", name=op.f('ck_ImportBatch_status_valid')),
    sa.ForeignKeyConstraint(['SourceId'], ['Source.SourceId'], name=op.f('fk_ImportBatch_SourceId_Source')),
    sa.PrimaryKeyConstraint('ImportBatchId', name=op.f('pk_ImportBatch'))
    )
    op.create_table('ManufacturerAlias',
    sa.Column('ManufacturerAliasId', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ManufacturerId', sa.BigInteger(), nullable=False),
    sa.Column('Alias', sa.NVARCHAR(length=200), nullable=False),
    sa.Column('NormalizedAlias', sa.NVARCHAR(length=200), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.Column('UpdatedAt', sa.DateTime(), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.ForeignKeyConstraint(['ManufacturerId'], ['Manufacturer.ManufacturerId'], name=op.f('fk_ManufacturerAlias_ManufacturerId_Manufacturer'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ManufacturerAliasId', name=op.f('pk_ManufacturerAlias')),
    sa.UniqueConstraint('NormalizedAlias', name=op.f('uq_ManufacturerAlias_NormalizedAlias'))
    )
    op.create_table('FieldMapping',
    sa.Column('FieldMappingId', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ImportBatchId', sa.BigInteger(), nullable=False),
    sa.Column('SourceFieldName', sa.NVARCHAR(length=200), nullable=False),
    sa.Column('CanonicalFieldName', sa.NVARCHAR(length=100), nullable=False),
    sa.Column('MappingMethod', sa.NVARCHAR(length=50), nullable=False),
    sa.Column('Confidence', sa.NVARCHAR(length=10), nullable=False),
    sa.Column('Evidence', sa.NVARCHAR(length=500), nullable=True),
    sa.Column('UserApproved', mssql.BIT(), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.CheckConstraint("Confidence IN ('HIGH','MEDIUM','LOW')", name=op.f('ck_FieldMapping_confidence_valid')),
    sa.ForeignKeyConstraint(['ImportBatchId'], ['ImportBatch.ImportBatchId'], name=op.f('fk_FieldMapping_ImportBatchId_ImportBatch'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('FieldMappingId', name=op.f('pk_FieldMapping'))
    )
    op.create_table('ProductLine',
    sa.Column('ProductLineId', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('BrandId', sa.BigInteger(), nullable=False),
    sa.Column('Name', sa.NVARCHAR(length=200), nullable=False),
    sa.Column('NormalizedName', sa.NVARCHAR(length=200), nullable=False),
    sa.Column('ThreadType', sa.NVARCHAR(length=100), nullable=True),
    sa.Column('Material', sa.NVARCHAR(length=100), nullable=True),
    sa.Column('Weight', sa.NVARCHAR(length=50), nullable=True),
    sa.Column('Finish', sa.NVARCHAR(length=100), nullable=True),
    sa.Column('Status', sa.NVARCHAR(length=20), nullable=False),
    sa.Column('Metadata', sa.NVARCHAR(), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.Column('UpdatedAt', sa.DateTime(), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.ForeignKeyConstraint(['BrandId'], ['Brand.BrandId'], name=op.f('fk_ProductLine_BrandId_Brand')),
    sa.PrimaryKeyConstraint('ProductLineId', name=op.f('pk_ProductLine')),
    sa.UniqueConstraint('BrandId', 'NormalizedName', name='uq_brand_name')
    )
    op.create_table('SourceFile',
    sa.Column('SourceFileId', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ImportBatchId', sa.BigInteger(), nullable=False),
    sa.Column('OriginalFileName', sa.NVARCHAR(length=300), nullable=False),
    sa.Column('StoredFileName', sa.NVARCHAR(length=300), nullable=False),
    sa.Column('FileType', sa.NVARCHAR(length=20), nullable=False),
    sa.Column('FileSizeBytes', sa.BigInteger(), nullable=False),
    sa.Column('Sha256', sa.NVARCHAR(length=64), nullable=False),
    sa.Column('Metadata', sa.NVARCHAR(), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.Column('UpdatedAt', sa.DateTime(), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.ForeignKeyConstraint(['ImportBatchId'], ['ImportBatch.ImportBatchId'], name=op.f('fk_SourceFile_ImportBatchId_ImportBatch'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('SourceFileId', name=op.f('pk_SourceFile'))
    )
    op.create_table('SourceWorksheet',
    sa.Column('SourceWorksheetId', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('SourceFileId', sa.BigInteger(), nullable=False),
    sa.Column('WorksheetName', sa.NVARCHAR(length=200), nullable=False),
    sa.Column('SheetIndex', sa.Integer(), nullable=False),
    sa.Column('RowCount', sa.Integer(), nullable=False),
    sa.Column('ColumnCount', sa.Integer(), nullable=False),
    sa.Column('HeaderRowNumber', sa.Integer(), nullable=False),
    sa.Column('Metadata', sa.NVARCHAR(), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.Column('UpdatedAt', sa.DateTime(), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.ForeignKeyConstraint(['SourceFileId'], ['SourceFile.SourceFileId'], name=op.f('fk_SourceWorksheet_SourceFileId_SourceFile'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('SourceWorksheetId', name=op.f('pk_SourceWorksheet'))
    )
    op.create_table('Thread',
    sa.Column('ThreadId', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ProductLineId', sa.BigInteger(), nullable=False),
    sa.Column('CanonicalName', sa.NVARCHAR(length=200), nullable=True),
    sa.Column('Status', sa.NVARCHAR(length=20), nullable=False),
    sa.Column('Metadata', sa.NVARCHAR(), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.Column('UpdatedAt', sa.DateTime(), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.ForeignKeyConstraint(['ProductLineId'], ['ProductLine.ProductLineId'], name=op.f('fk_Thread_ProductLineId_ProductLine')),
    sa.PrimaryKeyConstraint('ThreadId', name=op.f('pk_Thread'))
    )
    op.create_table('Color',
    sa.Column('ColorId', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ThreadId', sa.BigInteger(), nullable=False),
    sa.Column('Red', mssql.TINYINT(), nullable=True),
    sa.Column('Green', mssql.TINYINT(), nullable=True),
    sa.Column('Blue', mssql.TINYINT(), nullable=True),
    sa.Column('HexCode', sa.NVARCHAR(length=7), nullable=True),
    sa.Column('PmsCode', sa.NVARCHAR(length=50), nullable=True),
    sa.Column('PmsName', sa.NVARCHAR(length=100), nullable=True),
    sa.Column('LabL', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('LabA', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('LabB', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('XValue', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('YValue', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('ZValue', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('CalculationMethod', sa.NVARCHAR(length=50), nullable=False),
    sa.Column('CalculationVersion', sa.NVARCHAR(length=20), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.Column('UpdatedAt', sa.DateTime(), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.CheckConstraint("HexCode LIKE '#[0-9A-Fa-f][0-9A-Fa-f][0-9A-Fa-f][0-9A-Fa-f][0-9A-Fa-f][0-9A-Fa-f]'", name=op.f('ck_Color_hex_format')),
    sa.ForeignKeyConstraint(['ThreadId'], ['Thread.ThreadId'], name=op.f('fk_Color_ThreadId_Thread'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ColorId', name=op.f('pk_Color'))
    )
    op.create_table('RawRecord',
    sa.Column('RawRecordId', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('SourceWorksheetId', sa.BigInteger(), nullable=False),
    sa.Column('SourceRowNumber', sa.Integer(), nullable=False),
    sa.Column('RowHash', sa.NVARCHAR(length=64), nullable=False),
    sa.Column('RawPayload', sa.NVARCHAR(), nullable=False),
    sa.Column('ProcessingStatus', sa.NVARCHAR(length=20), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.CheckConstraint('ISJSON(RawPayload) = 1', name=op.f('ck_RawRecord_raw_payload_is_json')),
    sa.ForeignKeyConstraint(['SourceWorksheetId'], ['SourceWorksheet.SourceWorksheetId'], name=op.f('fk_RawRecord_SourceWorksheetId_SourceWorksheet'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('RawRecordId', name=op.f('pk_RawRecord'))
    )
    op.create_table('ThreadIdentifier',
    sa.Column('ThreadIdentifierId', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ThreadId', sa.BigInteger(), nullable=False),
    sa.Column('SourceId', sa.BigInteger(), nullable=False),
    sa.Column('IdentifierType', sa.NVARCHAR(length=50), nullable=False),
    sa.Column('IdentifierValue', sa.NVARCHAR(length=100), nullable=False),
    sa.Column('NormalizedValue', sa.NVARCHAR(length=100), nullable=False),
    sa.Column('IsPrimary', mssql.BIT(), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.Column('UpdatedAt', sa.DateTime(), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.ForeignKeyConstraint(['SourceId'], ['Source.SourceId'], name=op.f('fk_ThreadIdentifier_SourceId_Source')),
    sa.ForeignKeyConstraint(['ThreadId'], ['Thread.ThreadId'], name=op.f('fk_ThreadIdentifier_ThreadId_Thread'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ThreadIdentifierId', name=op.f('pk_ThreadIdentifier')),
    sa.UniqueConstraint('SourceId', 'IdentifierType', 'NormalizedValue', name='uq_source_type_value')
    )
    op.create_table('DataQualityIssue',
    sa.Column('DataQualityIssueId', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ImportBatchId', sa.BigInteger(), nullable=False),
    sa.Column('RawRecordId', sa.BigInteger(), nullable=True),
    sa.Column('Severity', sa.NVARCHAR(length=10), nullable=False),
    sa.Column('IssueType', sa.NVARCHAR(length=100), nullable=False),
    sa.Column('FieldName', sa.NVARCHAR(length=200), nullable=True),
    sa.Column('Message', sa.NVARCHAR(length=1000), nullable=False),
    sa.Column('SuggestedResolution', sa.NVARCHAR(length=500), nullable=True),
    sa.Column('Status', sa.NVARCHAR(length=20), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.Column('ResolvedAt', sa.DateTime(), nullable=True),
    sa.Column('ResolvedBy', sa.NVARCHAR(length=200), nullable=True),
    sa.CheckConstraint("Severity IN ('INFO','WARNING','ERROR','CRITICAL')", name=op.f('ck_DataQualityIssue_severity_valid')),
    sa.CheckConstraint("Status IN ('OPEN','RESOLVED','IGNORED')", name=op.f('ck_DataQualityIssue_status_valid')),
    sa.ForeignKeyConstraint(['ImportBatchId'], ['ImportBatch.ImportBatchId'], name=op.f('fk_DataQualityIssue_ImportBatchId_ImportBatch'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['RawRecordId'], ['RawRecord.RawRecordId'], name=op.f('fk_DataQualityIssue_RawRecordId_RawRecord')),
    sa.PrimaryKeyConstraint('DataQualityIssueId', name=op.f('pk_DataQualityIssue'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('DataQualityIssue')
    op.drop_table('ThreadIdentifier')
    op.drop_table('RawRecord')
    op.drop_table('Color')
    op.drop_table('Thread')
    op.drop_table('SourceWorksheet')
    op.drop_table('SourceFile')
    op.drop_table('ProductLine')
    op.drop_table('FieldMapping')
    op.drop_table('ManufacturerAlias')
    op.drop_table('ImportBatch')
    op.drop_table('Brand')
    op.drop_table('Source')
    op.drop_table('Manufacturer')
    # ### end Alembic commands ###
